# Generated by Django 4.2.11 on 2026-04-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='business_available',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='business_price',
            field=models.DecimalField(decimal_places=2, default=8000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='business_seats',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='economy_available',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='flight',
            name='economy_price',
            field=models.DecimalField(decimal_places=2, default=3000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='economy_seats',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='flight',
            name='first_available',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='first_price',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='first_seats',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='premium_economy_available',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='premium_economy_price',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='premium_economy_seats',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_type',
            field=models.CharField(default='economy', max_length=20),
        ),
    ]
