# Generated by Django 4.2.11 on 2026-04-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_flight_business_available_flight_business_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
